import csv
from flask_restful import Api, Resource, reqparse
import json

# CITY CODES
citycodesapi = [
    {'city_code': 'ALB', 'city_name': 'Albany'},
    {'city_code': 'ABQ', 'city_name': 'Albuquerque'},
    {'city_code': 'AMA', 'city_name': 'Amarillo'},
    {'city_code': 'AUA', 'city_name': 'Aruba'},
    {'city_code': 'ATL', 'city_name': 'Atlanta'},
    {'city_code': 'AUS', 'city_name': 'Austin'},
    {'city_code': 'BWI', 'city_name': 'Baltimore/Washington'},
    {'city_code': 'BZE', 'city_name': 'Belize City'},
    {'city_code': 'BLI', 'city_name': 'Bellingham'},
    {'city_code': 'BHM', 'city_name': 'Birmingham'},
    {'city_code': 'BOI', 'city_name': 'Boise'},
    {'city_code': 'BOS', 'city_name': 'Boston (Logan)'},
    {'city_code': 'BZN', 'city_name': 'Bozeman/Yellowstone'},
    {'city_code': 'BUF', 'city_name': 'Buffalo/Niagara'},
    {'city_code': 'BUR', 'city_name': 'Burbank'},
    {'city_code': 'CUN', 'city_name': 'Cancun'},
    {'city_code': 'CHS', 'city_name': 'Charleston'},
    {'city_code': 'CLT', 'city_name': 'Charlotte'},
    {'city_code': 'MDW', 'city_name': 'Chicago (Midway)'},
    {'city_code': 'ORD', 'city_name': 'Chicago - O"Hare'},
    {'city_code': 'CVG', 'city_name': 'Cincinnati'},
    {'city_code': 'CLE', 'city_name': 'Cleveland'},
    {'city_code': 'COS', 'city_name': 'Colorado Springs'},
    {'city_code': 'CMH', 'city_name': 'Columbus'},
    {'city_code': 'CRP', 'city_name': 'Corpus Christi'},
    {'city_code': 'CZM', 'city_name': 'Cozumel'},
    {'city_code': 'DAL', 'city_name': 'Dallas (Love Field)'},
    {'city_code': 'DEN', 'city_name': 'Denver'},
    {'city_code': 'DSM', 'city_name': 'Des Moines'},
    {'city_code': 'VPS', 'city_name': 'Destin/Ft Walton Beach'},
    {'city_code': 'DTW', 'city_name': 'Detroit'},
    {'city_code': 'ELP', 'city_name': 'El Paso'},
    {'city_code': 'EUG', 'city_name': 'Eugene'},
    {'city_code': 'FLL', 'city_name': 'Fort Lauderdale'},
    {'city_code': 'RSW', 'city_name': 'Fort Myers'},
    {'city_code': 'FAT', 'city_name': 'Fresno'},
    {'city_code': 'GCM', 'city_name': 'Grand Cayman'},
    {'city_code': 'GRR', 'city_name': 'Grand Rapids'},
    {'city_code': 'GSP', 'city_name': 'Greenville/Spartanburg'},
    {'city_code': 'HRL', 'city_name': 'Harlingen'},
    {'city_code': 'BDL', 'city_name': 'Hartford'},
    {'city_code': 'HAV', 'city_name': 'Havana'},
    {'city_code': 'ITO', 'city_name': 'Hilo (Hawaii Island)'},
    {'city_code': 'HNL', 'city_name': 'Honolulu (Oahu)'},
    {'city_code': 'HOU', 'city_name': 'Houston (Hobby)'},
    {'city_code': 'IAH', 'city_name': 'Houston BUSH'},
    {'city_code': 'IND', 'city_name': 'Indianapolis'},
    {'city_code': 'JAN', 'city_name': 'Jackson'},
    {'city_code': 'JAX', 'city_name': 'Jacksonville'},
    {'city_code': 'OGG', 'city_name': 'Kahului (Maui)'},
    {'city_code': 'MCI', 'city_name': 'Kansas City'},
    {'city_code': 'KOA', 'city_name': 'Kona (Hawaii Island)'},
    {'city_code': 'LAS', 'city_name': 'Las Vegas'},
    {'city_code': 'LIR', 'city_name': 'Liberia (Guanacaste)'},
    {'city_code': 'LIH', 'city_name': 'Lihue (Kauai)'},
    {'city_code': 'LIT', 'city_name': 'Little Rock'},
    {'city_code': 'LGB', 'city_name': 'Long Beach'},
    {'city_code': 'ISP', 'city_name': 'Long Island/Islip'},
    {'city_code': 'LAX', 'city_name': 'Los Angeles'},
    {'city_code': 'SJD', 'city_name': 'Los Cabos'},
    {'city_code': 'SDF', 'city_name': 'Louisville'},
    {'city_code': 'LBB', 'city_name': 'Lubbock'},
    {'city_code': 'MHT', 'city_name': 'Manchester'},
    {'city_code': 'MEM', 'city_name': 'Memphis'},
    {'city_code': 'MIA', 'city_name': 'Miami'},
    {'city_code': 'MAF', 'city_name': 'Midland/Odessa'},
    {'city_code': 'MKE', 'city_name': 'Milwaukee'},
    {'city_code': 'MSP', 'city_name': 'Minneapolis/St. Paul'},
    {'city_code': 'MBJ', 'city_name': 'Montego Bay'},
    {'city_code': 'MTJ', 'city_name': 'Montrose'},
    {'city_code': 'MYR', 'city_name': 'Myrtle Beach'},
    {'city_code': 'BNA', 'city_name': 'Nashville'},
    {'city_code': 'NAS', 'city_name': 'Nassau'},
    {'city_code': 'MSY', 'city_name': 'New Orleans'},
    {'city_code': 'LGA', 'city_name': 'New York (LaGuardia)'},
    {'city_code': 'ORF', 'city_name': 'Norfolk'},
    {'city_code': 'OAK', 'city_name': 'Oakland'},
    {'city_code': 'OKC', 'city_name': 'Oklahoma City'},
    {'city_code': 'OMA', 'city_name': 'Omaha'},
    {'city_code': 'ONT', 'city_name': 'Ontario/LA'},
    {'city_code': 'SNA', 'city_name': 'Orange County/Santa Ana'},
    {'city_code': 'MCO', 'city_name': 'Orlando'},
    {'city_code': 'ECP', 'city_name': 'Panama City Beach'},
    {'city_code': 'PNS', 'city_name': 'Pensacola'},
    {'city_code': 'PHL', 'city_name': 'Philadelphia'},
    {'city_code': 'PHX', 'city_name': 'Phoenix'},
    {'city_code': 'PIT', 'city_name': 'Pittsburgh'},
    {'city_code': 'PWM', 'city_name': 'Portland Maine'},
    {'city_code': 'PDX', 'city_name': 'Portland'},
    {'city_code': 'PVD', 'city_name': 'Providence'},
    {'city_code': 'PLS', 'city_name': 'Providenciales'},
    {'city_code': 'PVR', 'city_name': 'Puerto Vallarta'},
    {'city_code': 'PUJ', 'city_name': 'Punta Cana'},
    {'city_code': 'RDU', 'city_name': 'Raleigh/Durham'},
    {'city_code': 'RNO', 'city_name': 'Reno/Tahoe'},
    {'city_code': 'RIC', 'city_name': 'Richmond'},
    {'city_code': 'ROC', 'city_name': 'Rochester'},
    {'city_code': 'SMF', 'city_name': 'Sacramento'},
    {'city_code': 'SLC', 'city_name': 'Salt Lake City'},
    {'city_code': 'SAT', 'city_name': 'San Antonio'},
    {'city_code': 'SAN', 'city_name': 'San Diego'},
    {'city_code': 'SFO', 'city_name': 'San Francisco'},
    {'city_code': 'SJC', 'city_name': 'San Jose CA'},
    {'city_code': 'SJO', 'city_name': 'San Jose Costa Rica'},
    {'city_code': 'SJU', 'city_name': 'San Juan Puerto Rico'},
    {'city_code': 'SBA', 'city_name': 'Santa Barbara'},
    {'city_code': 'SRQ', 'city_name': 'Sarasota/Bradenton'},
    {'city_code': 'SAV', 'city_name': 'Savannah/Hilton Head'},
    {'city_code': 'SEA', 'city_name': 'Seattle/Tacoma'},
    {'city_code': 'GEG', 'city_name': 'Spokane'},
    {'city_code': 'STL', 'city_name': 'St. Louis'},
    {'city_code': 'HDN', 'city_name': 'Steamboat Springs (Hayden)'},
    {'city_code': 'SYR', 'city_name': 'Syracuse'},
    {'city_code': 'TPA', 'city_name': 'Tampa'},
    {'city_code': 'TUS', 'city_name': 'Tucson'},
    {'city_code': 'TUL', 'city_name': 'Tulsa'},
    {'city_code': 'IAD', 'city_name': 'Washington (Dulles)'},
    {'city_code': 'DCA', 'city_name': 'Washington (Reagan National)'},
    {'city_code': 'PBI', 'city_name': 'West Palm Beach'},
    {'city_code': 'ICT', 'city_name': 'Wichita'}
]


class apiv1(Resource):
    def get(self):
        return citycodesapi

    def post(self):
        print(self)
        parser = reqparse.RequestParser()
        parser.add_argument('city_code', type=str)
        parser.add_argument('city_name', type=str)

        args = parser.parse_args()

        print(args)
